let keywords = {
    "angry": "Take a deep breath, you will feel better in no time.",
    "sad": "Do something that makes you happy, like listening to music.",
    "happy": "Keep doing what makes you happy!",
    "bad": "Things will get better, don't worry!",
    "antisocial": "Try looking at social gatherings around your area so you can find people who share the same interests as you, be bold!", 
    "social": "It is always important to have some time for yourself, make sure you give yourself a day to relax and chill out.",
    "not good": "There are a lot of things in this world that are bad, you just have to learn how to make the best of it!",
    "boring":"Be the change you want to see in the world! Your boredom is only temporary.",
    "chaotic":"Modern day life can be extremely stressful and chaotic, but it is important to keep striving towards your goal and believing in yourself!",
    "chill":"Although it is good to take a break make sure to have a goal in mind.",
    "jealous":"Focus on yourself. There is no point in dwelling over things other people have.",
    "clingy":"Make sure to assert your boundries in all your relationships in order to feel comfortable.",
    "difficult":"It is good to take a break, but make sure you know when to continue on! Forward soldier, march on! Remember, you can do this!",
    "struggling":"Keep working hard! I know you can do it! Just remember to take a break once in a while.",
    "hate":"It is okay not to like everything all the time. Sometimes you just have to be okay, with having your own opinions.",
    "horrible":"It is okay to have a bad day. You do not have to be happy 24/7. Keep in mind that you are human!",
    "give up":"Have a little more confidence! Keeping a positive mindset will make things easier for you to do. Do not give up so soon! Keep trying.",
    "depressed": "Life gets tough, but that is okay. Keep working through it!",
    "busy":"Be sure that you have time for yourself! Try and keep yourself organized so that things dont get too much for you.",
    "tired":"I know things can be exhausting, be sure to take breaks and refresh your head.",
    "exhausted":"I see that you are tired. Make sure to get some rest and continue on once you are in the right mental space.",
    "enjoyable":"That is great! It is important to have a great time.",
    "fine":"It's great that youre doing fine. Hopefully that fine into great",
    "overwhelmed":"I can tell that this may be stressful, dont worry life gets better despite your hard situation now.",
    "overwhelming":"I can tell that this may be stressful, dont worry life gets better despite your hard situation now.",
    "stressing":"Things may be stressful but remember that you got this and that you have the ability to dictate your life!",
    "stressed":"Things may be stressful  you got this and that you have the ability to dictate your life!",
    "stressful":"Things may be stressful but remember that you got this and that you have the ability to dictate your life!",
    "cool":"I am glad that youre having a fun time.",
    "frustrating":"Be sure to take a break from stressful situations. Refresh your head then come back stronger than ever! I believe in you!",
    "amazing": "I am glad things are going so well for you!",
    "mad": "Try and keep a positive attitude! You will get more stuff done with a positive mindset rather than a negative one.",
    "angry": "Try and keep a positive attitude! You will get more stuff done with a positive mindset rather than a negative one.", 
    "great": "I am so glad it went great! Keep at it!",
    "productive": "Keep up the good work! I believe in you!",
    "lonely": "If youre feeling lonely, remember, you hvae me to keep you company! I promise things will get better.",
    "anxious": "I can tell that things may be overwhelming and stressful, but it will get better soon!",
    "tiring": "If youre feeling tired, take a moment to rest and keep up the good work!",
    "bored": "Be the change you want to see in the world! Your boredom is only temporary.",
    "disapointed":"I am sorry things have not been going so well, but try and look on the bright side of things!",
    "disapointing": "I am sorry things have not been going so well, but try and look on the brigt side of things!",
    "pain":"Your scars will grow to heal. You will be okay!",
    "painful":"Your scars will grow to heal. You will be okay!",
    "energetic":"It is great that you have a lot of energy! Keep up the good work. And put your energy to good use!",
    "exhilerated":"It is great that you are feeling exhilarated! You deserve to feel excited about something.",
    "exhilerating":"It is great that you are feeling exhilarated! You deserve to feel excited about something.",
    "interesting": "It is good that things have been interesting!",
    "intense": "If things are too much, remember to take a mental rest and then come back stronger than ever!",
    "calm":"Make sure to find time in your life to keep calm. It is very important for your mental health.",
    "confusing":"I know that you will be able to seek clarity! You got this!",
    "confused":"I know that you will be able to seek clarity! You got this!",
    "ready":"Its so amazing that you feel ready for whats next. You got this!", 
    "crazy":"Things can be crazy sometimes, but they will calm down soon.",
    "hurt":"I can sense your pain, but scars will grow to heal.",
    "hurting": "I can sense your pain, but your scars will grow to heal.",
    "lost":"If you are lost take time to find yourself again before continuing on with this stressful life."
}